Models/Course.cs
namespace SkySea_Commerce.Models;

public class Course
{
    public int Id { get; set; }
    public string Title { get; set; }
    public string Image { get; set; }
    public bool IsActive { get; set; }
    public bool IsHome { get; set; }

    
}

Models/ErrorViewModel.cs
namespace SkySea_Commerce.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Product.cs
namespace SkySea_Commerce.Models;

public class Product
{
    public int Id { get; set; }
    public string? productTitle { get; set; }
    public string productDescription { get; set; } = null!;
    public double productPrice { get; set; }
    public string? productImage { get; set; }
    public bool isAvailable { get; set; }
    public int productQuantity { get; set; }
    public bool IsHome { get; set; }

}

Controllers/CourseController.cs
using SkySea_Commerce.Models;
using Microsoft.AspNetCore.Mvc;

namespace SkySea_Commerce.Controllers
{
    public class CourseController : Controller
    {
        List<Course> courses = new List<Course>{
                    new Course { Id = 1 , Title = "C# Programming", Image = "c-sharp.png", IsActive = true , IsHome = true},
                    new Course { Id = 2 , Title = "Python Programming", Image = "python.jpg", IsActive = true , IsHome = true },
                    new Course { Id = 3 , Title = "Java Programming", Image = "java.jpg", IsActive = true , IsHome = false },
                    new Course { Id = 4 , Title = "Angular Programming", Image = "angular.jpg", IsActive = true , IsHome = false },
            };
        public ActionResult Index()
        {
            return View(courses);
        }




        public ActionResult List()
        {
            // Course[] courses = [course1, course2, course3];

            return View(courses);
        }

        public ActionResult Details(int id)
        {
            Course? course = courses.Where(a => a.Id == id).FirstOrDefault();


            return View(course);
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
namespace SkySea_Commerce.Controllers;

public class HomeController : Controller

{
    
    public ActionResult Index()
    {
        int number1 = 10;
        int number2 = 20;
        int sum = number1 + number2;

        ViewData["Sum"] = sum; 

        return View(); 

    }
    
    public ActionResult About()
    {
        return View(); 
    }

    
    public ActionResult Contact() 
    {
        return View();
    }

}

Controllers/ProductsController.cs
using SkySea_Commerce.Models;
using Microsoft.AspNetCore.Mvc;

namespace SkySea_Commerce.Controllers;

public class ProductsController : Controller
{
    List<Product> products =
        [
            new Product{
                Id = 1,
                productTitle = "iPhone 16",
                productDescription = "iPhone 16 128GB, Ultramarine",
                productPrice = 70.000,
                productImage = "iPhone-16.jpeg",
                isAvailable = true,
                IsHome = true
            },
            new Product{
                Id = 2,
                productTitle = "iPhone 16e",
                productDescription = "iPhone 16e 128GB, White",
                productPrice = 50.000,
                productImage = "iPhone-16e.jpeg",
                isAvailable = true,
                IsHome = true
            },
            new Product{
                Id = 3,
                productTitle = "iPhone 16 Pro",
                productDescription = "iPhone 16 Pro 128GB, Desert Titanium",
                productPrice = 90.000,
                productImage = "iPhone-16-pro.jpeg",
                isAvailable = true,
                IsHome = false
            },



        ];
    public ActionResult Index()
    {
        List<Product> productS = products.Where(p => p.IsHome).ToList();
        return View(productS);
    }


    public ActionResult List()
    {

        return View(products);
    }

    public ActionResult Details(int id)
    {

        Product? product = products.Where(p => p.Id == id).FirstOrDefault();

        return View(product);
    }


}

Views/Course/Details.cshtml
@model Course

<div class="row justify-content-center">
     <div class="col-8">

        <div class="card">
            <img src="~/img/@Model.Image" class="card-img-top" alt="">
            <div class="card-body">
                <h5 class="card-title">@Model.Title</h5>
                <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi, nemo?</p>
                <a href="#" class="card-link">Analyze</a>
            </div>

        </div>

    </div>
</div>

Views/Course/Index.cshtml
@model List<Course>

<div class="d-flex justify-content-between align-items-center">
    <h1 class="h3 b-3">Courses</h1>
    <a class="btn btn-outline-danger" asp-controller="Course" asp-action="List">All Courses</a>
</div>
<div class="row">

    @foreach (Course course in Model)
    {
        @if (course.IsHome)
        {
            <div class="col-md-4">
                @await Html.PartialAsync("_CourseCard", course)
            </div>
        }
    }



</div>

Views/Course/List.cshtml
@* @model Course[]  *@
@* @model IEnumerable<Course> *@
@model List<Course>

<h1 class="h3 b-3">All Courses</h1>

<div class="row">

    @foreach (Course course in Model)
    {
        <div class="col-md-3">
         @await Html.PartialAsync("_CourseCard",course)
         </div>
    }
</div>

Views/Course/_CourseCard.cshtml
 @model Course
 <div class="col">

        <div class="card mb-3">
            <img src="~/img/@Model.Image" class="card-img-top" alt="">
            <div class="card-body">
                <h5 class="card-title">@Model.Title</h5>
                <a asp-controller ="Course" asp-action="Details" asp-route-id="@Model.Id" class="btn btn-sm btn-secondary">Analyze</a>
            </div>

        </div>

    </div>

Views/Home/About.cshtml
<h1>Home/About</h1>

Views/Home/Contact.cshtml
<h1>Home/Contact</h1>

Views/Home/Index.cshtml
<h1>Home/Index</h1>

<p>
    @ViewData["sum"]
</p>

Views/Products/Details.cshtml
@model Product


<div class="row border">
    <div class="col-4">
        <img src="~/img/@Model.productImage" alt="" class="img-fluid" />

    </div>
    <div class="col-8 border-start p-3">
        <h1>
            @Model.productTitle

        </h1>
        <p>
            @Model.productDescription
        </p> 
        <p>
            @Model.productPrice
        </p>

        @if (Model.isAvailable)
        {
            @if (Model.productQuantity > 0)
            {
                <p>
                    Available
                </p>
            }
            else
            {
                <p>
                    Not enough stock
                </p>
            }

        }
        else
        {
            <p>
                Not available
            </p>
        }




    </div>

</div>

Views/Products/Index.cshtml
@model List<Product>

<div class="d-flex justify-content-between align-items-center">
    <h1 class="h3 b-3">Products</h1>
    <a class="btn btn-outline-danger" asp-controller="Products" asp-action="List">All Products</a>
</div>

<div class="row">
    @foreach (Product product in Model)
    {
        @if (product.isAvailable)
        {
            <div class="col-md-3">
                @await Html.PartialAsync("_ProductCard", product)
            </div>
        }
    }
</div>

Views/Products/List.cshtml
@model List<Product>


<div class="row">
    @foreach (Product product in Model)
    {
        @if (product.isAvailable)
        {
            <div class="col-md-3">
                @await Html.PartialAsync("_ProductCard", product)
            </div>
        }
    }
</div>

Views/Products/_ProductCard.cshtml
@model Product

<div class="card mb-3 shadow">

    <img src="~/img/@Model.productImage" class="card-img-top p-3 pt-0">


    <div class="card-body bg-light">
        <h5 class="card-title"> @Model.productTitle </h5>
        <p class="card-text"> @Model.productDescription </p>
        @if (!Model.isAvailable)
        {
            <p>Not Available</p>
        }
        <a asp-controller="Products" asp-action="Details" asp-route-id="@Model.Id"
            class="btn btn-outline-secondary d-flex justify-content-center"> Details </a>
    </div>

</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" integrity="sha512-jnSuA4Ss2PkkikSOLtYs8BlYIeeIK1h99ty4YfvRPAlzr377vr3CXDb7sb7eEEBYjDtcYj+AjBH3FLv5uSJuXg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <title>Document</title>
</head>
<body>
    <header>
    @await Html.PartialAsync("_Navbar")
    </header>
    <main class="container my-3">

            @RenderBody()
    </main>
    
</body>
</html>

Views/Shared/_Navbar.cshtml
<nav class=" navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
        <div class="container">
            <a class="navbar-brand" href="/">App</a>

            <ul class="navbar-nav me-auto">
                  <li class="nav-item">
                    <a class="nav-link active" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" asp-controller="Course" asp-action="Index">Course</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" asp-controller="Products" asp-action="Index">Products</a>
                </li>

            </ul>
        </div>
    </nav>